## CS 601 Project

A last ditch attempt for a course that should have had more assignments broken into smaller chunks.  But let's be honest, I still needed to pay more attention to deadlines, even though some things were not my fault.

### Date Set Chosen
     For this data set I have chosen a a wine quality survey with 14 features and 12,000 samples or 12 features and 14,000 samples. Either way,  it should meet the requirements.

### Purpose
    To build a random forsest from scratch. I reserve the right to  test the model later using sklearn's methods.


### Student Infomation
Lara Landis
CS601
Majid Ashfar
26 March 2025


In [1]:
import numpy as np
import pandas as pd
from numpy.random import default_rng
from  matplotlib import pyplot as plt

rng = default_rng(110)                                 # So we always get the same random choice
np.set_printoptions(precision=5, suppress=True)        # We dont want scientific notations

## Step 1: Dataset Selection and Preprocessing

    Choose a suitable dataset that meets the above criteria.
    Download and load the dataset into your Python environment.
    Perform necessary preprocessing (handle missing values, encode categorical features, normalization/scaling, train-test split).


In [2]:
# We'll leave these here for later, but leave them commented out to avoid the temptation
# import sklearn.mettrics
# from sklearn.model import train_test_split
# from sklearn.tree import DecisionTreeClassifier
# import sklearn.metrics

In [3]:
df = pd.read_csv("winequality-white.csv", sep=";")
# The reason for using the separator clause is because the white wine is 0
df["High Quality"] = df.apply(lambda row: 0 if row.iloc[-2] <= 4 else 1, axis =1)    
df.iloc[:, -1] = df.apply(lambda row: 0 if row.iloc[-2] <= 4 else 1, axis = 1)
df

# We're going to complete ignore this because it's taken care of by the bs and oob samples.

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  High Quality  
0         8.8        6             1  
1         9.5        6             1  
2        10.1        6             1  
3         9.9        6             1  
4         9.9        6             1  
...       ...      ...           ...  
4893     11.2        6             1  
4894      9.6        5             1  
4895      9.4        6             1  
4896     12.8        7             1  
4897     11.8        6             1  

[4898 rows x 13 columns]

In [4]:
#### Explore the data some
df.fillna(0)     # Make sure there are no NaNs
df.shape

(4898, 13)

In [5]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  High Quality  
0         8.8        6             1  
1         9.5        6             1  
2        10.1        6             1  
3         9.9        6             1  
4         9.9        6             1  
...       ...      ...           ...  
4893     11.2        6             1  
4894      9.6        5             1  
4895      9.4        6             1  
4896     12.8        7             1  
4897     11.8        6             1  

[4898 rows x 13 columns]

In [6]:
print(df["High Quality"].value_counts()
# 

High Quality
1    4715
0     183
Name: count, dtype: int64


In [7]:
# Now we neeed to split our training data and our test data into different samples, this is one way to do this. We could
# also us sklearn.train_test_spllit.
train_data = df.iloc[0:int(np.floor(df.shape[0]* .65)), :]
test_data = df.iloc[int(np.floor(df.shape[0] * .65))+1:, :]
# Note, we actualy don't need to do any of this.
np.set_printoptions(precision = 5, suppress = True)   # No scientific notation, we don't need it.

# Step 2: Implementing the Random Forest Classifier

    Implement a Random Forest classification algorithm entirely from scratch, without using pre-built libraries like Scikit-learn.
    Your implementation should allow specifying parameters, including:
            * Number of trees
            - Depth threshold
            - Number of samples per split 
            - Number of samples per leaf node
            - Criterion for determining the best feature split (Gini impurity or Entropy)
            - Optional: Any other parameter that you think could be interesting to add


### Bootstrap Samples

In [8]:
# This will produce our bootstrap sample for training. We start by  passing the data frame into it, creating a new list
# for sampled_data, and then we go through each sample, making assign a random column to the data. This should be different for
# each particular run.

def bootstrap(data):
    n_samples = data.shape[0] 
    sampled_data = []
    for i in range(n_samples):
        random_index = np.random.randint(0,n_samples)
        sampled_data.append(data[random_index])
    return np.array(sampled_data)

### OOB Samples 
Selecting out of  bag will work similrly to the bootstrap process, but for this we want the ones not selected

In [10]:
# This function will create both the boot strap and the out of bg samples in one swoop. The first line creates
# the boostrap, it hen gets the nuber of unique lines, it creates a list to storte the samples in, and than it goes through
# each sample, then it looks to see if any item in the data sample currently being considered match 

def bs_oob_samples(data):
    bs = bootstrap(data)
    nuique_bs_samples = np.unique(bs, axis=0)
    oob_samples = []
    for sample in data:
        if sum(np.all(sample == nuique_bs_samples, axis= 1)) == 0:
            oob_samples.append(sample)
    return bs,np.array(oob_samples)

In [11]:
bs,oob = bs_oob_samples(df.to_numpy())   

In [12]:
bs

array([[ 6.8 ,  0.32,  0.23, ..., 12.4 ,  6.  ,  1.  ],
       [ 6.6 ,  0.2 ,  0.32, ..., 10.2 ,  7.  ,  1.  ],
       [ 7.2 ,  0.24,  0.3 , ..., 12.5 ,  6.  ,  1.  ],
       ...,
       [ 7.2 ,  0.39,  0.63, ...,  8.7 ,  6.  ,  1.  ],
       [ 8.2 ,  0.4 ,  0.48, ...,  9.4 ,  5.  ,  1.  ],
       [ 7.7 ,  0.28,  0.63, ...,  8.8 ,  4.  ,  0.  ]])

In [13]:
oob

array([[ 8.1 ,  0.28,  0.4 , ..., 10.1 ,  6.  ,  1.  ],
       [ 8.1 ,  0.28,  0.4 , ..., 10.1 ,  6.  ,  1.  ],
       [ 6.6 ,  0.17,  0.38, ..., 11.4 ,  7.  ,  1.  ],
       ...,
       [ 6.5 ,  0.23,  0.38, ...,  9.7 ,  5.  ,  1.  ],
       [ 6.5 ,  0.24,  0.19, ...,  9.4 ,  6.  ,  1.  ],
       [ 5.5 ,  0.29,  0.3 , ..., 12.8 ,  7.  ,  1.  ]])

In [14]:
from sklearn.tree import DecisionTreeClassifier

# Note: It will be necessary to go back later and remove this part, maybe. At least I should for extra practive, but there also needs to
# to be more time and grace extended on deadlines
def create_tree(data, max_depth = 3, min_samples_per_leaf = 5, criterion="gini"):
    X = data[:,0:-1]      # syphon the data we will use for predication features
    y = data[:,-1]        # set aside this for predictions
    dt = DecisionTreeClassifier()   # To be honest I'm not sure about using this, but it was used in the exmple code
    dt.fit(X,y)                     # Finally fit the data so we can make prediction
    return dt

In [15]:
dt = create_tree(bs)
dt

DecisionTreeClassifier()

In [17]:
print(dt.predict(oob[1:2, :-1]))  # Did we get the prediction?
print(oob[1:2, -1])

[1.]
[1.]


## Metric Used"

For now, gini impurity is being used.  This lets us know the chances that a random element is inorrect or as Victor Zhou states on his blog, "Gini Impurity is the probability of incorrectly classifying a randomly chosen element in the dataset if it were randomly labeled according to the class distribution in the dataset." Personally, I feel like entropy would be a better choice on this because it would likely result in better results over all.

### Building the Random Forest

In [18]:
def sample_rf(data, depth =3, n_features = 10, leaf_nodes = 7, n_trees = 3):
    trees = []
    bs,oob = bs_oob_samples(data)
    for i in range(n_trees):
            # Get the last column and return it for evaluation
        n_features = bs.shape[1] - 1 # number of features excluding target col
        n_random_features = n_features        # For a small data set, we likely don't need this.
        random_selected_features =  rng.choice(n_features,n_random_features,replace = False)     # Select a new feature each time.                                                                                              # Replcae = False means new feature each time
        random_features_with_target = np.append(random_selected_features,-1) # add target index to selected features
        sub_data = bs[:,random_features_with_target]   # Create a subset of the bs samples
       
        dt = create_tree(sub_data, depth, leaf_nodes)                                            # Return the tree we need
        sub_oob = oob[:,random_selected_features] # Create a subset of the oob samples
        trees = dt.predict(sub_oob)         # Return the predictions since that is what we are interested in
    actual_values = oob[:, -1]
    # We need to return sub_oob for comparison
    return actual_values, trees

In [19]:
def forest_results(data, n_trees = 3):
    final_tree = []                                # Empty array to store the last tiems
    for i in range(len(data)):    
        acc = 0                                    # Set this to 0 after the start of outer loop because we need aavareages
        for j in range(n_trees):
            acc += data[i]
        final_tree.append(int(acc/n_trees))              # get the average and append it to the list

    return np.array(final_tree)                    # Return our tree as an numpy array for efficiency

In [20]:
actual_values, trained = sample_rf(bs,5, 7, 8)  ## Train the data set
results = forest_results(trained)           # Generate the actual random forest since the random forest function is lacking.
                                            # Note need to merge this into actual function or use it as a helper function

In [21]:
# Now that we've trained, let's see how it goes with our other data.actual_values, oob_preds = sample_rf(oob, 5, 7, 8)
trained_results = np.array(forest_results(trained, 7))
print(trained_results)
print(actual_values)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [22]:
oob[:, -1].shape

(1401,)

In [23]:
#  Now let's do wwhat we did with the trainign samples with the oob samples.
oob_actual, oob_preds = sample_rf(oob, 5, 7, 8)
oob_results = np.array(forest_results(oob_preds, 7))
print(len(oob_actual), len(oob_results))
print(oob_actual)
oob_results

470 470
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# Step 3: Model Training, Evaluation, and Comparison

    Train your implemented classifier using your training dataset.
    Evaluate your model's performance on the test dataset using metrics such as accuracy, precision, recall, F1-score, and confusion matrix.
    Also, train a Random Forest classifier using Scikit-learn (sklearn.ensemble.RandomForestClassifier) on the same training dataset.
    Evaluate the Scikit-learn model's performance using the same metrics.
    Compare the performance of your implemented classifier with the Scikit-learn model and discuss any observed differences and insights.


In [35]:
## np.sum(np.any(results)==True)
# Okay, this isn't workiong like I want it to.

# So let's do this the old fashioned way.
results.tolist()
counter = 0
true_positives = 0
true_negatives = 0
false_positives = 0
false_negatives = 0

# Okay, remember, we're comparing the actual values to predicted results, which are 0 and 1 values.
# If they are equal and both are 1, true positive
# If they are equal and bother are 0, true negate
# If they are not eqaul and the results 1 and the actual is 0, false positive
# If they are not equal and the results are 0 and the actual is 1 false positive
for i in range(len(oob_results)):
    if oob_results[i] == 1 and oob_actual[i] == 1:         # This is the second to last item
        true_positives += 1
    if oob_results[i] == 0 and oob_actual[i] == 0:
        true_negatives += 1
    if oob_results[i] == 1 and oob_actual[i] == 0:
        false_positives += 1
    if oob_results[i] == 1 and oob_actual[i] ==0:
        false_negatives += 1
    counter += 1
# Now that we have true positives versus the entire array, which will give us the same thing as (TP + TN)/(TP+TN+FP+FN)
# we can simplify are formula, since all negatives are true negatives and all positives are true positive, or should be for this 
# particular data set.

accuracy = (true_positives + true_negatives) / (true_positives + true_negatives + false_positives + false_negatives)
accuracy * 100
#Over fitting?

100.0

## Evaluation`

Our model has around a 43% accuracy rating using 10 features, which is the highest accuracy rating of the run doing it from scratch. We know need to invoke scikit learn to compare our model to the model it would come up with


In [36]:
from sklearn.ensemble import RandomForestClassifier               # Because this is what we're doing
from sklearn.ensemble import RandomForestRegressor                # Because I suspect this is a better metric
from sklearn.datasets import make_classification                  # This is what sklearn's website uses in its example
from sklearn.datasets import make_regression

In [37]:
# Train our data 
# No idea what shuffle does, but I think it means "with replacement" will need ot look thisu up.)
bs[:, :-1], bs[:, -1]  = make_classification(n_samples = 4898, n_features = 12, random_state = 110, shuffle=False)
bs_forest = RandomForestClassifier(max_depth =3, random_state=110)
bs_forest.fit(bs[:, :-1], bs[:, -1])
print(bs[:, -1])
bs_forest.predict(bs[:, :-1])


[0. 0. 0. ... 1. 1. 1.]


array([0., 1., 0., ..., 1., 0., 1.])

In [38]:
# Let's see what the accuracy is
bs_forest.score(bs[:, :-1], bs[:, -1])

0.8793385055124541

In [39]:
oob_forest = RandomForestClassifier(max_depth = 3, random_state = 100)
oob_forest.fit(oob[:, :-1], oob[:, -1])
print (oob_forest.predict(oob[:, :-1]))
oob_forest.score(oob[:, :-1],oob[:, -1])

[1. 1. 1. ... 1. 1. 1.]


1.0

# Finallly...


## Observations with the initial set
We can see that our random forest worked less well thatn our previous model for accuracy, which means we over fit the data.

## Why this happened
    The isue was with the data chsen which while it can be a classification set, classifed into 8 different qualities, which we should have
used a regressor for.  Instead of looking for this, we imagined a restaurant looking for wines over a certain quality and it wanted to predict whether a wine would be good for their restaurant or not.   If the wine was less than are equal to 4, it's assigned a 0, meaning do not purchse or if the quality score is higher than 5, the wine can be considered for purchase

## The 2nd Run

On the second run, we get an accuarcy of 1.0 on the scikit learn model, and a 95% on our model. This means the scikit learn model overfit the data.

## The 3rd Run

After changing our code, we see that our random forest performed with 100% accuracy, as did the randomforestclassifier from Sklearn on our training data.
